### ISSUE TITLE
Add build specific environment variables

### ISSUE THREAD

**Issue by relekang** [frigg/frigg-worker#144]
- [x] `FRIGG_PULL_REQUEST_ID`
- [x] `FRIGG_BUILD_BRANCH`
- [x] `FRIGG_BUILD_COMMIT_HASH`
- [x] `FRIGG_BUILD_NUMBER`
- [x] `FRIGG_BUILD_DIR`
- [x] `FRIGG_WORKER`
- [x] `FRIGG_DOCKER_IMAGE`

**Comment by relekang** [comment]
@frecar Anything else that would be useful? Should we prefix with `FRIGG_`?

**Comment by frecar** [comment]
Yes, I think it is smart to prefix all env variables with FRIGG_

What about BUILD_WORKER, for debugging?

**Comment by relekang** [comment]
:+1:
