### ISSUE TITLE
Clean up old containers from disk 

### ISSUE THREAD

**Issue by frecar** [frigg/frigg-worker#73]

**Comment by relekang** [comment]
Is there more than `docker rm`, [which we already do](https://github.com/frigg/docker-wrapper-py/blob/master/docker/manager.py#L225), that we can do?

**Comment by frecar** [comment]
Hmm, maybe not.. But one of the workers had 20+ containers on disk after a
while.. Maybe it's caused by failed builds?

**Comment by relekang** [comment]
Yes, either crashes or workers that are restartet in the middle of a build.
